### ISSUE TITLE
Add more Country Flags

### ISSUE THREAD

**Issue by Zaid-maker** [bumb7ebee/weather-profile-actions#1]
Please add more Flags i don't find my country and find this action very useful, Rn there is only Turkey flag

**Comment by Zaid-maker** [comment]
Thanks!

**Comment by bumb7ebee** [comment]
Hi @Zaid-maker ,

thank you for reacting to me! It seems to be fulfilling its functionality in this current state. I'm trying to make this more stable.

Please stay tuned. Best regards.

**Comment by Zaid-maker** [comment]
> Hi @Zaid-maker ,
> 
> thank you for reacting to me! It seems to be fulfilling its functionality in this current state. I'm trying to make this more stable.
> 
> Please stay tuned. Best regards.

Yes, i just saw that u updated the README which is looking fire 🔥 Keep Going

**Comment by bumb7ebee** [comment]
> > Hi @Zaid-maker ,
> > thank you for reacting to me! It seems to be fulfilling its functionality in this current state. I'm trying to make this more stable.
> > Please stay tuned. Best regards.
> 
> Yes, i just saw that u updated the README which is looking fire 🔥 Keep Going

Thank you!
