### ISSUE TITLE
Unable to resolve action `bumb7ebee/weather-profile-actions@v1.0.0`, unable to find version `v1.0.0`

### ISSUE THREAD

**Issue by Zaid-maker** [bumb7ebee/weather-profile-actions#2]
Getting this error:

![image](https://github.com/bumb7ebee/weather-profile-actions/assets/53424436/13593b9d-4da5-4eae-b168-941ea87a3213)

**Comment by bumb7ebee** [comment]
> Getting this error:
> 
> ![image](https://github.com/bumb7ebee/weather-profile-actions/assets/53424436/13593b9d-4da5-4eae-b168-941ea87a3213)
> 

Hi @Zaid-maker ,

From now on, I will continue with the v1 tag. I will update v1 too every time I create a new version. For example, v1.0.0 >> v1, v1.0.1 >> v1, v1.2.0 >> v1, etc. The benefit of this is that you will not have to constantly change the version number every time a new version is created; the v1 tag will always point to the latest stable version. So you need to change v1.0.0 to v1 in your yaml file now. Thank you for your understanding.

**Comment by Zaid-maker** [comment]
> Hi @Zaid-maker ,
> 
> From now on, I will continue with the v1 tag. I will update v1 too every time I create a new version. For example, v1.0.0 >> v1, v1.0.1 >> v1, v1.2.0 >> v1, etc. The benefit of this is that you will not have to constantly change the version number every time a new version is created; the v1 tag will always point to the latest stable version. So you need to change v1.0.0 to v1 in your yaml file now. Thank you for your understanding.

Thanks <3
